//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEFW7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int IdDireccion { get; set; }
        public int IdPersona { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string Detalles { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
